package Tema2.Calculadora;


import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Peanf
 */
public class Tema2Ejercicio2 extends javax.swing.JFrame {

    /**
     * Creates new form Tema2Ejercicio2
     */
    public Tema2Ejercicio2() {
        initComponents();
        calculadora();
    }
    
    public void calculadora (){
        JPanel panelOperaciones1 = new JPanel();
        panelOperaciones1.setLayout(new GridLayout(2, 1));
   
        panelOperaciones1.add(new JButton("X"));
        panelOperaciones1.add(new JButton("/"));
        
        JPanel numeros = new JPanel();
        numeros.setLayout(new GridLayout(4, 3));
        numeros.add(new JButton("7"));
        numeros.add(new JButton("8"));
        numeros.add(new JButton("9"));
        numeros.add(new JButton("4"));
        numeros.add(new JButton("5"));
        numeros.add(new JButton("6"));
        numeros.add(new JButton("1"));
        numeros.add(new JButton("2"));
        numeros.add(new JButton("3"));
        numeros.add(new JButton("0"));
        numeros.add(new JButton("="));

        JPanel panelOperaciones2 = new JPanel();
        panelOperaciones2.setLayout(new GridLayout(2, 1));
   
        panelOperaciones2.add(new JButton("-"));
        panelOperaciones2.add(new JButton("+"));
        
  // Configurar el JFrame principal
        this.setLayout(new BorderLayout());
        this.add(panelOperaciones1,  BorderLayout.WEST);  
        this.add(numeros, BorderLayout.CENTER);        
        this.add(panelOperaciones2, BorderLayout.EAST);        

        setVisible(true);          
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 499, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 407, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tema2Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tema2Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tema2Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tema2Ejercicio2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tema2Ejercicio2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
